# Generated by Django 5.2.6 on 2025-09-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='career_objective',
            field=models.TextField(default='To leverage my expertise in statistics, programming and information technology to provide innovative, data-driven solutions and effectively address complex statistical and IT challenges.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Expert statistician and data scientist with extensive experience in healthcare research, data management, and programming.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='mosotieno25@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='happy_clients',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Otieno Moses Ochieng', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+254-719648375', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects_completed',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(default='Data Scientist | Statistician | Python & R Expert | Healthcare Research', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Data Scientist & Statistician', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_experience',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
